# -------------
# Selenium Grid
#docker-compose up --scale chrome=3 --scale firefox=3
# -------------
version: "3"
services:
  hub:
    image: selenium/hub:3.11
    ports:
      - "4444:4444"
    environment:
      - GRID_MAX_SESSION=10
    #healthcheck:
      #test: curl --fail -s http://192.168.0.106:4444/ || exit 1
      #interval: 1m30s
      #timeout: 10s
      #start_period: 15s
      #retries: 3
  chrome:
    image: selenium/node-chrome:3.11
    depends_on:
      - hub
    ports:
      - "5551:5595"
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSIONS=5
    #healthcheck:
      #test: curl --fail -s http://http://192.168.0.106:4444/wd/hub/static/resource/hub.html | grep No Sessions || exit 1
      #interval: 1m30s
      #timeout: 10s
      #start_period: 15s
      #retries: 3
  firefox:
    image: selenium/node-firefox:3.11
    shm_size: '1gb'
    depends_on:
      - hub
    ports:
      - "5501:5545"
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSIONS=5
    #healthcheck:
      #test: curl --fail -s http://http://192.168.0.106:4444/wd/hub/static/resource/hub.html | grep No Sessions || exit 1
      #interval: 1m30s
      #timeout: 10s
      #start_period: 15s
      #retries: 3
# ==== TESTS after grid is starting on demand ========
  smoke-tests:
    image: hiperion/tests
    depends_on:
      - chrome
      - firefox
    environment:
      #- HUB_HOST=hub
      #- BROWSER=firefox
      - MODULE=test-smoke.xml
    volumes:
      - /mnt/volume/output/tests/smoke:/usr/share/tests/test-output      
  functional-tests:
    image: hiperion/tests
    depends_on:
      - chrome
      - firefox
    environment:
      #- HUB_HOST=hub
      #- BROWSER=firefox
      - MODULE=test-functional.xml
    volumes:
      - /mnt/volume/output/tests/functional:/usr/share/tests/test-output  
      
